# API Configurations
api:
  name: "${api.name}"
  version: "${project.version}"
  #Replace with respective autodiscovery id
  autodiscoveryID: "16422509"
  
# Listener configuration  
https:
  host: "0.0.0.0"
  port: "8082"
  
# API Configuration
jira-exp-api:
  http-listener:
    path: "/api/issue-updates"

# AMQ Configurations
anypoint-mq:
  case-update-dl-queue-name: "accelerator-salesforce-case-update-jira-dl-queue"
  server-url: "https://mq-eu-west-2.anypoint.mulesoft.com/api/v1"
  ackTimeout: "1000"
  frequency: "1000"
  case-update-queue-name: "accelerator-salesforce-update-case-queue-jira"
  fetchSize: "10"
  client-id:  "26a6eb20edf340349522fbfc52b63ce3" 
  #client-secret: "overridden during deploy time"

# Retry configuration 
retry:
   amq: 
    delayMillisecs: "3000"
    numRetries: "3"
tls:
    keyStorepass: "pass123"
    password: "pass123"
    
# Reconnect configuration 
reconnection:
     amq:
      frequency: "2000"
      attempts: "2"

# Customize the application messages in the below section
application-msgs:
  #Data publish success message
  success-message: "Data Published To Queue Successfully"
  #Before Connector logger message
  before-connector-call-message: "Before Connector Call"
  #After Connector logger message
  after-connector-call-message: "After Connector Call"
  #Local Exception logger message
  local-exception-handler-message: "Exception has occured"
  success-flag: "true"
