# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.
# API Configurations
anypoint-mq:
    
    client-secret: "![rqyenApMNzzRa2tauiqQM8HinSLU4eL3e0Fsxhpy/wa7D3Kgvp0a0g==]"